[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'; default-src 'none' https: *.apple.com; object-src 'none'; script-src 'self'; style-src 'self' fonts.googleapis.com; img-src https: *; connect-src 'self'; font-src fonts.gstatic.com"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"