[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'; default-src https: *.apple.com; object-src 'none'; script-src 'self'; style-src 'self' fonts.googleapis.com; img-src https: *; connect-src 'self'; font-src fonts.gstatic.com"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Cache-Control = "public, max-age=5, s-maxage=36000, must-revalidate"

[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://hachyderm.io/.well-known/webfinger?resource=acct:nirina@hachyderm.io"
  status = 200