name: deploy
on:
  workflow_call:
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  deploy-bons-comptes-bons-amis:
    if: github.ref == 'refs/heads/main'
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BONS_COMPTES_BONS_AMIS_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 11
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest turbo

      - name: Pull vercel environments
        run: vercel pull --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy bons comptes bons amis
        run: npx turbo-ignore --fallback=HEAD~10 -d ./apps/bons-comptes-bons-amis || vercel deploy --prod --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}

  deploy-blog:
    if: github.ref == 'refs/heads/main'
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BONS_COMPTES_BONS_AMIS_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - name: Use Node.js 20
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Cache turbo build setup
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Install turbo
        run: pnpm i -g turbo

      - run: turbo build --filter nirina-blog

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './apps/blog/.vitepress/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_BLOG_SITE_ID }}
        timeout-minutes: 1

  deploy-site:
    if: github.ref == 'refs/heads/main'
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SITE_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 11
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest turbo

      - name: Pull vercel environments
        run: vercel pull --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy bons comptes bons amis
        run: npx turbo-ignore --fallback=HEAD~10 -d ./apps/nirina-site || vercel deploy --prod --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}
