name: deploy
on:
  push:
    branches:
      - main
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  deploy-bons-comptes-bons-amis:
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BONS_COMPTES_BONS_AMIS_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 11
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest turbo

      - name: Pull vercel environments
        run: vercel pull --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy bons comptes bons amis
        run: npx turbo-ignore -d ./apps/bons-comptes-bons-amis || vercel deploy --prod --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}

  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 11
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Install turbo CLI
        run: pnpm install --global turbo

      - run: pnpm install --ignore-scripts

      - name: set deploy key to pull content
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
      - run: ./pull-blog-content.sh
        working-directory: ./apps/nirina-site
      - run: turbo build --filter nirina-site

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@4cbaf4c08f1a7bfa537d6113472ef4424e4eb654 # v3.0
        with:
          publish-dir: './apps/nirina-site/dist'
          netlify-config-path: './apps/nirina-site/netlify.toml'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_BLOG_SITE_ID }}
        timeout-minutes: 1
