name: deploy
on:
  push:
    branches:
      - main
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  deploy-bons-comptes-bons-amis:
    environment: Production – bons-comptes-bons-amis
    env:
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 11
      - uses: pnpm/action-setup@v4
        with:
          version: 9.14.4
      - name: Use Node.js 20
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest turbo

      - name: Pull vercel environments
        run: vercel pull --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy bons comptes bons amis
        run: npx turbo-ignore -d ./apps/bons-comptes-bons-amis || vercel deploy --prod --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}

  deploy-site:
    environment: Production – blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.14.4
      - name: Use Node.js 20
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install turbo CLI
        run: pnpm install --global turbo

      - run: pnpm install

      - name: set deploy key to pull content
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
          ./pull-blog-content.sh
        working-directory: ./apps/nirina-site
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_BLOG_SITE_ID }}
        run: |
          pnpm install -g netlify-cli@17.37.2
          netlify deploy --filter nirina-site --build --prod --message "${{ github.event.head_commit.message }}"

  deploy-sudoku-musique:
    environment: Production – generateur-musique-app-sudoku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.14.4
      - name: Use Node.js 20
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install turbo CLI
        run: pnpm install --global turbo

      - run: pnpm install --ignore-scripts

      - run: turbo build --filter=generateur-musique --filter=generateur-sudoku
      - name: Deploy Sudoku to Netlify
        uses: nwtgck/actions-netlify@4cbaf4c08f1a7bfa537d6113472ef4424e4eb654 # v3.0
        with:
          publish-dir: './apps/generateur-sudoku/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_GENERATEUR_SUDOKU_SITE_ID }}
        timeout-minutes: 1
      - name: Deploy Generateur Musique to Netlify
        uses: nwtgck/actions-netlify@4cbaf4c08f1a7bfa537d6113472ef4424e4eb654 # v3.0
        with:
          publish-dir: './apps/generateur-musique/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_GENERATEUR_MUSIQUE_SITE_ID }}
        timeout-minutes: 1
      - name: Deploy Generateur Musique to Netlify
        uses: nwtgck/actions-netlify@4cbaf4c08f1a7bfa537d6113472ef4424e4eb654 # v3.0
        with:
          publish-dir: './apps/generateur-musique/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_GENERATEUR_ETHEREUM_VANITY_SITE_ID }}
        timeout-minutes: 1

  deploy-ethereum-generateur:
    environment: Production – ethereum-wallet-generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.14.4
      - name: Use Node.js 20
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install turbo CLI
        run: pnpm install --global turbo

      - run: pnpm install --ignore-scripts

      - run: turbo build --filter=ethereum-wallet-generator
      - name: Deploy Generateur Musique to Netlify
        uses: nwtgck/actions-netlify@4cbaf4c08f1a7bfa537d6113472ef4424e4eb654 # v3.0
        with:
          publish-dir: './apps/ethereum-wallet-generator/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_GENERATEUR_ETHEREUM_VANITY_SITE_ID }}
        timeout-minutes: 1

  deploy-jeu-du-debat:
    environment: Production – jeu-du-debat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.14.4
      - name: Use Node.js 20
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install turbo CLI
        run: pnpm install --global turbo

      - run: pnpm install --ignore-scripts

      - run: turbo build --filter=jeu-du-debat
      - name: Deploy Generateur Musique to Netlify
        uses: nwtgck/actions-netlify@4cbaf4c08f1a7bfa537d6113472ef4424e4eb654 # v3.0
        with:
          publish-dir: './apps/jeu-du-debat/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_JEU_DU_DEBAT_SITE_ID }}
        timeout-minutes: 1
