name: ci
on:
  push:
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
permissions:
  contents: read # for checkout
jobs:
  ci:
    runs-on: ubuntu-24.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v4
        with:
          version: 10.6.2
      - name: Use Node.js 20
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Cache turbo build setup
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install turbo
        run: pnpm i -g turbo

      - run: pnpm format:check
      - run: turbo test:unit --concurrency=1

      - run: turbo build
