name: ci
on:
  push:
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
permissions:
  contents: read # for checkout
jobs:
  ci:
    runs-on: ubuntu-22.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v4
        with:
          version: 9.14.4
      - name: Use Node.js 20
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Cache turbo build setup
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install turbo
        run: pnpm i -g turbo

      - run: turbo test:unit --concurrency=1

      - run: turbo build
