name: e2e-nirina-site
on:
  push:
    paths:
      - .github/workflows/**
      - apps/nirina-site/**
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
permissions:
  contents: read # for checkout
jobs:
  e2e:
    environment: Preview – blog
    runs-on: ubuntu-24.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.1+sha512.1acb565e6193efbebda772702950469150cf12bcc764262e7587e71d19dc98a423dff9536e57ea44c49bdf790ff694e83c27be5faa23d67e0c033b583be4bfcf
      - name: Use Node.js 20
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Cache turbo build setup
        uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Install turbo
        run: pnpm i -g turbo
      - run: turbo build --filter=nirina-site
      - name: Deploy to Netlify
        id: deploy-to-netlify
        uses: nwtgck/actions-netlify@4cbaf4c08f1a7bfa537d6113472ef4424e4eb654 # v3.0
        with:
          publish-dir: './apps/nirina-site/dist'
          netlify-config-path: './apps/nirina-site/netlify.toml'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_BLOG_SITE_ID }}
        timeout-minutes: 1
      - run: echo "PLAYWRIGHT_URL=$(echo ${{ steps.deploy-to-netlify.outputs.deploy-url }})" >> $GITHUB_ENV
      - name: Install playwright browsers
        run: |
          pnpm exec playwright install
          pnpm exec playwright install-deps
      - run: turbo test:e2e --filter=nirina-site
