name: ci
on:
  push:
jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.1
      - name: Use Node.js 20
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: pnpm install
      - name: Install turbo
        run: pnpm i -g turbo

      - name: Run build
        run: turbo build
      - name: Run test:unit
        run: turbo test:unit
      - name: Install playwright browsers
        run: pnpm exec playwright install
      - name: Install playwright browsers
        run: pnpm exec playwright install-deps
      - name: Install python
        run: pip install -r requirements.txt
        working-directory: packages/bons-comptes-bons-amis
      - name: Run e2e
        run: turbo test:e2e
