name: pnpm test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install && pnpm i -g turbo
      - name: Run test:unit
        run: turbo test:unit
      - name: Run build
        run: turbo build
      - name: Run e2e
        run: turbo test:e2e
