name: 'test-on-push'

on: [push]

# This workflow will build your tauri app without uploading it anywhere.

jobs:
  test-tauri:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: pnpm install # change this to npm, pnpm or bun depending on which one you use.

      - name: lint frontend app
        run: pnpm lint
      - name: test frontend app
        run: pnpm test
      - name: test rust app
        working-directory: ./src-tauri
        run: cargo test
      - name: build frontend app
        run: pnpm tauri build
